// Convert a real snarkjs Groth16 (BN254) proof + verifying key into the byte
// layout expected by Stellar's bn254 host functions, and emit:
//   1. contracts/veil_verifier/src/fixture.rs  — consts for the Rust test
//   2. circuits/onchain.json                    — hex, for deploy + frontend
//
// Host encoding:
//   Fr/Fp  : 32-byte big-endian
//   G1Affine: be(X) || be(Y)                               (64 bytes)
//   G2Affine: be(X.c1)||be(X.c0)||be(Y.c1)||be(Y.c0)       (128 bytes)
// snarkjs gives G2 coords as [c0, c1], so we emit c1 first.
// proof.A is negated (−A) because the contract pairing uses e(−A,B)·…

import * as snarkjs from 'snarkjs'
import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { commitmentOf, nullifierHashOf, buildTree, merkleProof } from './lib/veilTree.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))

// BN254 base field prime (Fq), for point negation.
const FQ = 21888242871839275222246405745257275088696311157297823662689037894645226208583n

function rand() {
  const b = crypto.getRandomValues(new Uint8Array(31))
  let x = 0n
  for (const v of b) x = (x << 8n) + BigInt(v)
  return x % FQ
}

function to32BE(dec) {
  let x = BigInt(dec)
  const out = new Uint8Array(32)
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(x & 0xffn)
    x >>= 8n
  }
  return out
}
function concat(arrs) {
  const len = arrs.reduce((n, a) => n + a.length, 0)
  const out = new Uint8Array(len)
  let o = 0
  for (const a of arrs) {
    out.set(a, o)
    o += a.length
  }
  return out
}
// G1 [x, y, "1"] -> be(x)||be(y)
const g1 = (p) => concat([to32BE(p[0]), to32BE(p[1])])
// G2 [[x0,x1],[y0,y1],...] -> be(x1)||be(x0)||be(y1)||be(y0)
const g2 = (p) =>
  concat([to32BE(p[0][1]), to32BE(p[0][0]), to32BE(p[1][1]), to32BE(p[1][0])])
// negate A: [x, Fq - y]
const negG1 = (p) => concat([to32BE(p[0]), to32BE((FQ - (BigInt(p[1]) % FQ)) % FQ)])

const hex = (u8) => Buffer.from(u8).toString('hex')
const rustArr = (u8) => `[${Array.from(u8).join(', ')}]`

async function main() {
  // Build a small org and prove eligibility for one member.
  const N = 8
  const members = []
  for (let i = 0; i < N; i++) {
    const nullifier = rand()
    const secret = rand()
    members.push({ nullifier, secret, commitment: await commitmentOf(nullifier, secret) })
  }
  const { root, layers } = await buildTree(members.map((m) => m.commitment))
  const idx = 3
  const me = members[idx]
  const { pathElements, pathIndices } = merkleProof(layers, idx)
  const nullifierHash = await nullifierHashOf(me.nullifier)
  const recipient = rand()

  const input = {
    root: root.toString(),
    nullifierHash: nullifierHash.toString(),
    recipient: recipient.toString(),
    nullifier: me.nullifier.toString(),
    secret: me.secret.toString(),
    pathElements: pathElements.map(String),
    pathIndices: pathIndices.map(String),
  }

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    join(__dirname, 'veil_js', 'veil.wasm'),
    join(__dirname, 'veil_final.zkey')
  )
  const vk = JSON.parse(readFileSync(join(__dirname, 'verification_key.json'), 'utf8'))

  // Sanity: must verify off-chain first.
  const ok = await snarkjs.groth16.verify(vk, publicSignals, proof)
  if (!ok) throw new Error('off-chain verify failed; aborting')

  const alpha = g1(vk.vk_alpha_1)
  const beta = g2(vk.vk_beta_2)
  const gamma = g2(vk.vk_gamma_2)
  const delta = g2(vk.vk_delta_2)
  const ic = vk.IC.map(g1)
  const pa = negG1(proof.pi_a)
  const pb = g2(proof.pi_b)
  const pc = g1(proof.pi_c)
  const signals = publicSignals.map(to32BE)

  // ---- Rust verifying key (stable across proofs; embedded in the contract) ----
  const icRust = ic.map((b) => `    ${rustArr(b)},`).join('\n')
  const vkRs = `// AUTO-GENERATED by circuits/export_fixture.mjs — do not edit by hand.
// Groth16 verifying key (BN254) for the Veil circuit, in Stellar host byte order.
#![allow(clippy::all)]
pub const ALPHA: [u8; 64] = ${rustArr(alpha)};
pub const BETA: [u8; 128] = ${rustArr(beta)};
pub const GAMMA: [u8; 128] = ${rustArr(gamma)};
pub const DELTA: [u8; 128] = ${rustArr(delta)};
pub const IC: [[u8; 64]; ${ic.length}] = [
${icRust}
];
`
  writeFileSync(join(__dirname, '..', 'contracts', 'veil_verifier', 'src', 'vk.rs'), vkRs)

  // ---- Rust test fixture (one concrete proof + its public signals) ----
  const sigRust = signals.map((b) => `    ${rustArr(b)},`).join('\n')
  const fixtureRs = `// AUTO-GENERATED by circuits/export_fixture.mjs — do not edit by hand.
// A single valid proof + its public signals, used by the contract tests.
#![allow(clippy::all)]
pub const PROOF_A: [u8; 64] = ${rustArr(pa)};
pub const PROOF_B: [u8; 128] = ${rustArr(pb)};
pub const PROOF_C: [u8; 64] = ${rustArr(pc)};
pub const SIGNALS: [[u8; 32]; ${signals.length}] = [
${sigRust}
];
`
  writeFileSync(join(__dirname, '..', 'contracts', 'veil_verifier', 'src', 'fixture.rs'), fixtureRs)

  // ---- JSON for deploy + frontend ----
  const json = {
    root: hex(to32BE(root)),
    vk: {
      alpha: hex(alpha),
      beta: hex(beta),
      gamma: hex(gamma),
      delta: hex(delta),
      ic: ic.map(hex),
    },
    proof: { a: hex(pa), b: hex(pb), c: hex(pc) },
    signals: signals.map(hex),
  }
  writeFileSync(join(__dirname, 'onchain.json'), JSON.stringify(json, null, 2))

  console.log('off-chain verify: OK')
  console.log('public signals  :', publicSignals)
  console.log('wrote contracts/veil_verifier/src/fixture.rs and circuits/onchain.json')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
